- doc/tools/qubes-dom0-update.rst
- doc/tools/qvm-sync-appmenus.rst
Counterpart to https://github.com/QubesOS/qubes-core-admin/pull/94
> Remove dates from man pages (2/3)

- dom0-updates/qubes-dom0-update
Closes QubesOS/qubes-issues#1445
> Flush dnf configuration on updateVM before starting dom0 update

- dom0-updates/qubes-dom0-update
Per issue https://github.com/QubesOS/qubes-issues/issues/2848
Also moved "exit 1" block to end of conditional block for better chance of success.
> Fix root.img handling bug

- dom0-updates/qubes-receive-updates
Fixes [QubesOS/qubes-core-admin-linux#2815](https://github.com/QubesOS/qubes-issues/issues/2815).
> Switch to createrepo_c

- dom0-updates/qubes-dom0-update
qvm-run auto-starts VMs by default
> qubes-dom0-update: Simplify

- dom0-updates/qubes-dom0-update
I started this just to fix 'avaliable' but found a couple other minor cases.
> Fix typos in qubes-dom0-update

- dom0-updates/qubes-dom0-update
I didn't change any of the variable names because it made me nervous and I was too lazy to test.
> Fix some references to `yum` instead of `dnf`

- dom0-updates/patch-dnf-yum-config
- dom0-updates/qubes-dom0-update
- dom0-updates/qubes-dom0-updates.cron
- rpm_spec/core-dom0-linux.spec.in
Unify updates notification, disabling updates.
And a little cleanup.
> Fixes for dom0 update mechanism

- .travis.yml
- qrexec/qrexec-client.c
> Fix GCC8 warning

- dom0-updates/qubes-dom0-update
(This commit is applicable to the release4.0 branch as well.)
> qubes-dom0-update: Quote arguments

- system-config/75-qubes-dom0.preset
used by https://github.com/QubesOS/qubes-core-qrexec/pull/6
references QubesOS/qubes-issues#5125
> Added enabling of qrexec-policy-daemon.service

- dom0-updates/qubes-dom0-update
Fixes QubesOS/qubes-issues#5562
> Don't pass stdin to VMs unless necessary. 

- dom0-updates/qubes-dom0-update
> qubes-dom0-update: fix missing '&&'

- dom0-updates/qfile-dom0-unpacker.c
Add a safety mesure to ensure we have enought place on dom0 rootfs
> dom0-updates: double default max updates bytes

- dom0-updates/qubes-dom0-update
This adds proper quoting and replaces strings with arrays where
applicable.  It also protects dom0 by displaying DNF’s output in an
UpdateVM.
Fixes QubesOS/qubes-issues#6321.
> qubes-dom0-update: handle -- and metacharacters

- Makefile
- rpm_spec/core-dom0-linux.spec.in
Fixes https://github.com/QubesOS/qubes-issues/issues/5826
> Fix autoextend

- dracut/dracut.conf.d/30-qubes.conf
- dracut/dracut.conf.d/extra-modules.conf
- dracut/dracut.conf.d/qubes-disable-network.conf
- dracut/dracut.conf.d/qubes-pciback.conf
- dracut/dracut.conf.d/verbosity.conf
- rpm_spec/core-dom0-linux.spec.in
Fixes QubesOS/qubes-issues#6691
> Reduce dracut verbosity

- rpm_spec/core-dom0-linux.spec.in
> spec: add BR make

- dracut/modules.d/90qubes-pciback/install
- dracut/modules.d/90qubes-pciback/installkernel
- dracut/modules.d/90qubes-pciback/module-setup.sh
- dracut/modules.d/90qubes-pciback/qubes-pciback.sh
- rpm_spec/core-dom0-linux.spec.in
- system-config/75-qubes-dom0.preset
- system-config/qubes-usb-rules.conf
- system-config/qubes-usbguard.conf
- system-config/usbguard.service
Shell scripts are a terrible choice for critical code like this, but they are the best choice available, sadly.
> Try to make pciback more robust

- dracut/modules.d/90qubes-pciback/module-setup.sh
- system-config/qubes-usbguard.conf
- system-config/usbguard.service
Fixes two of the minor issues I mentioned at https://github.com/QubesOS/qubes-issues/issues/7248
> usbguard: some fixes

- dracut/modules.d/90qubes-pciback/module-setup.sh
- dracut/modules.d/90qubes-pciback/qubes-pciback.sh
That should hopefully be all for now though.
> usbguard: more fixes

- Makefile
- rpm_spec/core-dom0-linux.spec.in
- setup.py
- vmupdate/agent/entrypoint.py
- vmupdate/agent/source/apt/allow_release_info_change.py
- vmupdate/agent/source/apt/apt_api.py
- vmupdate/agent/source/apt/apt_cli.py
- vmupdate/agent/source/apt/configuration.py
- vmupdate/agent/source/args.py
- vmupdate/agent/source/common/package_manager.py
- vmupdate/agent/source/common/stream_redirector.py
- vmupdate/agent/source/dnf/configuration.py
- vmupdate/agent/source/dnf/disable_deltarpm.py
- vmupdate/agent/source/dnf/dnf_api.py
- vmupdate/agent/source/dnf/dnf_cli.py
- vmupdate/agent/source/dnf/manage_rpm_macro.py
- vmupdate/agent/source/utils.py
- vmupdate/qube_connection.py
- vmupdate/update_manager.py
- vmupdate/vmupdate.py
A simple updater that uses the apt/dnf python packages or the direct cli command to update templates.
Implementing [#7443](https://github.com/QubesOS/qubes-issues/issues/7443)
> Non-interactive template updater

- doc/tools/qvm-sync-appmenus.rst
Closes QubesOs/qubes-issues#6848
> Update manpage for qvm-sync-appmenus

- vmupdate/agent/entrypoint.py
- vmupdate/agent/source/apt/allow_release_info_change.py
- vmupdate/agent/source/apt/apt_api.py
- vmupdate/agent/source/apt/apt_cli.py
- vmupdate/agent/source/apt/configuration.py
- vmupdate/agent/source/args.py
- vmupdate/agent/source/common/package_manager.py
- vmupdate/agent/source/common/process_result.py
- vmupdate/agent/source/common/progress_reporter.py
- vmupdate/agent/source/common/stream_redirector.py
- vmupdate/agent/source/dnf/configuration.py
- vmupdate/agent/source/dnf/disable_deltarpm.py
- vmupdate/agent/source/dnf/dnf_api.py
- vmupdate/agent/source/dnf/dnf_cli.py
- vmupdate/agent/source/dnf/manage_rpm_macro.py
- vmupdate/agent/source/log_congfig.py
- vmupdate/qube_connection.py
- vmupdate/update_manager.py
- vmupdate/vmupdate.py
add progress bars and refactor&cleanup
> qubes-vm-update: a parallel progress bars

- dom0-updates/qubes-dom0-update
Do not refuse update of release candidate of Xen.
> dom0-update: fix handling -rc xen version

- rpm_spec/core-dom0-linux.spec.in
https://github.com/QubesOS/qubes-issues/issues/5009
> Remove unnecessary ImageMagick build requirement

- dom0-updates/qfile-dom0-unpacker.c
- dom0-updates/qubes-dom0-update
- dom0-updates/qubes-receive-updates
- rpm_spec/core-dom0-linux.spec.in
- system-config/75-qubes-dom0.preset
See individual commits for details.
QubesOS/qubes-issues#6982
> Changes for Fedora 37 based dom0

- vmupdate/agent/source/dnf/dnf_api.py
- vmupdate/qube_connection.py
- vmupdate/update_manager.py
- vmupdate/vmupdate.py
> prb/updater: more option

- dom0-updates/qubes-dom0-update
- dom0-updates/qubes-receive-updates
See commit description and referenced issue for details.
Fixes QubesOS/qubes-issues#8015
> dom0-updates: revert displaying updatevm output in xterm

- vmupdate/agent/entrypoint.py
- vmupdate/agent/source/args.py
- vmupdate/agent/source/common/package_manager.py
- vmupdate/agent/source/common/process_result.py
- vmupdate/agent/source/dnf/dnf_api.py
- vmupdate/agent/source/log_congfig.py
- vmupdate/agent/source/status.py
- vmupdate/qube_connection.py
- vmupdate/update_manager.py
- vmupdate/vmupdate.py
Sending a SIGINT signal now causes a graceful shutdown, i.e. vms for which update has not started are canceled, but updates in progress are completed.
> qubes-vm-update: capture SIGINT

- dom0-updates/qubes-receive-updates
Do not allow leading special characters either.
> Do not allow trailing newlines in filenames

- dom0-updates/qubes-dom0-update
- system-config/11-qubes-ignore-zvol-devices.rules
- system-config/99z-qubes-mark-ready.rules
See individual commit messages for details.
> Misc improvements

- dom0-updates/qubes-dom0-update
UpdateVM might have a different default user.
> Avoid hardcoding user "user" in qubes-dom0-update

- vmupdate/vmupdate.py
fixes https://github.com/QubesOS/qubes-issues/issues/8162
> Skip double selecting of templates

- dom0-updates/qubes-dom0-update
- dom0-updates/qubes-dom0-updates.cron
fixes https://github.com/QubesOS/qubes-issues/issues/8240
> add update related features to dom0

- vmupdate/agent/entrypoint.py
- vmupdate/agent/source/apt/apt_api.py
- vmupdate/agent/source/args.py
- vmupdate/agent/source/common/progress_reporter.py
- vmupdate/agent/source/dnf/dnf_api.py
- vmupdate/qube_connection.py
helpful to diagnose https://github.com/QubesOS/qubes-issues/issues/8163
> more logging

- rpm_spec/core-dom0-linux.spec.in
- uki-generate
This is a prerequisite for secure boot.
Part of https://github.com/QubesOS/qubes-issues/issues/8206
> Add script to generate Xen unified kernel images

- vmupdate/agent/source/args.py
- vmupdate/agent/source/status.py
- vmupdate/update_manager.py
- vmupdate/vmupdate.py
fixes QubesOS/qubes-issues/issues/9031
> Updater: make selecting vms to restart/shutdown as same as in GUI version

- dom0-updates/qubes-dom0-update
fixes: https://github.com/QubesOS/qubes-issues/issues/6126
> Improve qubes-dom0-update messages

- doc/tools/qubes-vm-update.rst
- vmupdate/agent/entrypoint.py
- vmupdate/agent/source/apt/apt_api.py
- vmupdate/agent/source/apt/apt_cli.py
- vmupdate/agent/source/args.py
- vmupdate/agent/source/common/exit_codes.py
- vmupdate/agent/source/common/package_manager.py
- vmupdate/agent/source/dnf/dnf_cli.py
- vmupdate/agent/source/pacman/pacman_cli.py
- vmupdate/vmupdate.py
fixes QubesOS/qubes-issues/issues/6676
> after update cleanup 

- dom0-updates/qubes-dom0-update
fixes: https://github.com/QubesOS/qubes-issues/issues/6345
> Allow qubes-dom0-update concurrency on Audio Switch

- vmupdate/vmupdate.py
fixes: https://github.com/QubesOS/qubes-issues/issues/9565
> Print & log argument errors instead of just logging

- vmupdate/agent/source/common/package_manager.py
resolves: https://github.com/QubesOS/qubes-issues/issues/9617
also adding missing docstrings to make pylint happier
> Sort list of updated, installed & removed packages
