QubesOS/qubes-core-admin-linux

- appmenus-scripts/qubes-core-appmenus.py
This fixes a circular dependencies where get_attrs_config() in QubesVm is executed, before the self.storage is initialised. See also QubesOS/qubes-core-admin#6 (diff)
> Make appmenu paths properties and not config attrs

- appmenus-scripts/qubes-core-appmenus.py
- appmenus-scripts/qvm-appmenu-replace
This can be used to replace the Terminal shortcut (QubesOS/qubes-issues#1428).
> Add qvm-appmenu-replace tool.

- appmenus-scripts/qubes-receive-appmenus
After installing "codeblocks" app in TemplateVM it doesn't appear in Qubes VM Manager's available app shortcuts.
If I run in a Dom0 Terminal: /usr/libexec/qubes-appmenus/qubes-receive-appmenus fedora-23
I get this: "Warning: ignoring key 'Name' of codeblocks.desktop"
The "Name" key in that file has value "Code::Blocks"
The problem comes from line 168, because of the colons in the app Name.
By adding the colon ":" to the std_re used to match valid characters for "Name", the app is correctly parsed and I can add the shortcut to AppVMs
> Add colon (:) to trusted characters (for "Code::Blocks" appmenu)

- dom0-updates/qubes-dom0-update
This doesn't yet prevent appvms from starting with invalid template during the reinstall, and doesn't deal with the Netvm setting problem.
For issue #2061
> Support in-place template reinstalls - for testing

- system-config/75-qubes-dom0.preset
They will only start if booted with rd.antievilmaid anyway.
> Add AEM services to 75-qubes-dom0.preset

- qrexec/qrexec-client.c
Used by interactive shells and such. For example, I've saved the following as `qvm-shell` in dom0 to get an alright interactive VM shell with tab completion:
```
#!/bin/sh -e
if test $# = 0; then
echo "Usage: ${0##*/} [<qvm-run argument>...] <vm>" >&2
exit 1
fi
if test -t 0; then
stty_bak=$(stty -g)
trap "stty $stty_bak" EXIT
stty -echo -icanon  # disable echoing and line buffering
fi
qvm-run --pass-io "$@" \
"LC_ALL=C exec script --quiet --return /dev/null"  # fake a dumb TTY
```
> qrexec-client: Also allow the bell character

- dom0-updates/qubes-dom0-update
Use `script` (part of util-linux) to fake a dumb terminal in the updatevm, so dnf will show sync and download progress indicators.
> qubes-dom0-update: Show sync and download progress

- system-config/kernel-xen-efi.install
I need to set some flags in order to boot as described here: https://www.qubes-os.org/doc/uefi-troubleshooting/
My settings look like this:
```
$ efibootmgr -v
BootCurrent: 0000
Boot0000* Qubes HD(...)/File(\EFI\qubes\xen.efi)p.l.a.c.e.h.o...
```
which causes awk to get confused and think my $EFI_DIR should be:
```
/EFI/qubesp.l.a.c.e.h.o.l.d.e.r. ./.m.a.p.b.s. ./.n.o.e.x.i.t.b.o.o.t.
```
This causes the script to later bail:
```
if [ ! -d "$EFI_DIR" ]; then
exit 0;
fi
```
So my xen.cfg did not get new entries when installing dom0 kernel packages.
> Ignore EFI boot args when parsing for filename

- qrexec/qrexec-policy
@marmarek suggested in QubesOS/qubes-issues#1706 that the prompt to create a  default policy file should be hard to accept by default.
> Prompt to create policy file for qubes-rpc if not present.

- qrexec/qrexec-client.c
add specific message with respect to 'select' return value: error or timeout
> GCC7 fix fallthrough

- dom0-updates/qubes-dom0-update
Perhaps the UpdateVM template should be temporarily switched to the
backup too. That would make it really failsafe. Currently it requires
manual recovery (by setting template of UpdateVM to the backup).
> qubes-dom0-update: Adapt template backup failsafe for R4

- qrexec/qrexec-daemon.c
- only have one button, because "yes/no" makes no sense in this context
- inform use to use "-t pv" for xl console, because otherwise it won't
work for HVM domains.
- use the actual VM name, not "vmname"
before:
after:
before:
after:
> Improve qrexec protocol mismatch error dialog

- qrexec/qrexec-client.c
It's necessary to add the break at the end of "case -1" statement else the compiler will treat it as fall through and GCC 7 will throw an error because of -Werror=implicit-fallthrough=.
> Fix fall through

- dom0-updates/qubes-dom0-update
If for whatever reason /var/lib/qubes/dom0-updates was deleted or not created dom0 updates fail.
https://github.com/QubesOS/qubes-issues/issues/3620
> Make dir dom0-updates if it not exists on UpdateVM

- dom0-updates/qubes-dom0-update
If for whatever reason UpdateVM misses "/var/lib/qubes/dom0-updates", dom0 updates fail.
https://github.com/QubesOS/qubes-issues/issues/3620
> Make dir dom0-updates if not exists on UpdateVM

- system-config/kernel-grub2.install
- system-config/kernel-xen-efi.install
There are multiple places where initramfs can be created:
- /boot/iniramfs-*.img
- /boot/$MACHINE_ID/.../initrd (unused on Qubes, but created by Fedora
scripts)
- /boot/efi/EFI/.../initramfs-*.img
Do not generate all of those from scratch, but try to reuse existing
image (if exists). Since one dracut call may last even 5 minutes, this
change should greatly reduce installation time.
Fixes QubesOS/qubes-issues#3637
> kernel-install: avoid creating initramfs multiple times

- file-copy-vm/qvm-copy
- rpm_spec/core-dom0-linux.spec.in
While qvm-move and qvm-copy cannot work in dom0, their
absence is confusing. Thus, stub tools that output message
informing the user that these tools are unavailable and
qvm-move-to-vm/qvm-copy-to-vm should be used instead.
fixes QubesOS/qubes-issues#4021
> Added dummy qvm-move/qvm-copy do dom0

- dom0-updates/qubes-dom0-update
Fixed error with zenity in qubes-dom0-update --gui,
in which zenity was called with insufficient parameters.
fixes QubesOS/qubes-issues#4339
> Error in qubes-dom0-update --gui

- dom0-updates/qubes-dom0-update
Now we can do --action=info or --action=search
for a template. This will not shutdown the template and simply
execute search or info command for dnf.
> Adds info & search actions for template packages

- qrexec/qrexec-client.c
This caused qrexec-client to be killed when the local process
exited (by design) before consuming all the input, for instance
when receiving too much data for the admin.vm.volume.Import call.
> qrexec-client: ignore SIGPIPE

- dom0-updates/qubes-dom0-update
The actions are already supported at the remote end
(qubes-download-dom0-updates.sh).
This is in order to implement Salt functions for dom0, see
QubesOS/qubes-issues#5252.
> qubes-dom0-update: support 'list' and 'search' actions

- dracut/modules.d/90macbook12-spi-driver/module-setup.sh
- rpm_spec/core-dom0-linux.spec.in
A separate commit ``give vaio-fixes breath again`` is included to this PR.
I've back tracked the history, it looks like it was disabled by a mistake [during the refactoring](https://github.com/QubesOS/qubes-core-admin-linux/commit/a2139b95b599a4419e7787e1b37097d310771149#diff-5c2dc0ca076fcfeeae786070f88d5a16).
Not sure if this is the right approach of making these a dependency for qubes-core-dom0-linux package, but that works.
----
Parent PR: https://github.com/QubesOS/qubes-linux-kernel/pull/161
Related issue: https://github.com/QubesOS/qubes-issues/issues/3784
> [dom0, initramfs] add roadrunner2/macbook12-spi-driver configuration

- system-config/kernel-xen-efi.install
The original `sed` arguments caused the replacing of kernel parameters, for example, the default sleep mode parameter, `mem_sleep_default` would have it's value replaced with the kernel version being installed.
The solution is to only match the start of lines, as proposed by @marmarek 
Fixes QubesOS/qubes-issues#5716
> Fix kernel install script clobbering kernel params ending in default=

- dom0-updates/qfile-dom0-unpacker.c
Add support for -w option, which makes the extract process to wait for
enough free space in the target directory. This is especially useful
when restoring a backup, which is multi-stage asynchronous process -
wait for another process to process extracted files (and free the space)
before extracting more.
QubesOS/qubes-issues#5478
> qfile-dom0-unpacker: support waiting for free space

- dom0-updates/qubes-dom0-update
Salt parses the stdout of the command.  Therefore, if we are not showing
the remote command’s stdout, we need to run the command locally too.
> Run commands locally if not showing remote output

- dom0-updates/qubes-receive-updates
The old version was secure, but this is better 🙂:
- It doesn’t fail to detect a symlink in the event of an I/O error.
- It avoids a useless syscall.
- It avoids a useless regex match.
- It works no matter what the rpm macros are.
> qubes-dom0-update: improved signature checking

- Makefile
- dom0-updates/qubes-receive-updates
- rpm_spec/core-dom0-linux.spec.in
So that next RPM vuln will not make us issue a QSB 🙂.
This is the long-awaited rpmcanon integration.  It requires the
qubes-rpm-oxide component to be enabled in the build, as that component
provides rpmcanon.  Therefore, this cannot be merged until that component has been signed by a trusted key.
> rpmcanon integration

- system-config/00-qubes-ignore-devices.rules
These contain attacker-controlled data and must not be scanned by udev
> Skip encrypted volatile volumes

- dom0-updates/qubes-dom0-update
qvm-template is now a canonical tool to management. Redirect all
requests related to templates to appropriate qvm-template command
QubesOS/qubes-issues#2534
> qubes-dom0-update: redirect template management to qvm-template

- dom0-updates/qubes-receive-updates
The code to bypass rpmcanon didn’t actually work.  Furthermore, R4.1
uses the stock Fedora 32 RPM rather than a hardened fork, so bypassing
rpmcanon is significantly riskier.
> Remove option to bypass rpmcanon

- dom0-updates/qubes-dom0-update
The updatevm already downloads packages only (either using
--downloadonly option internally, or using yumdownloader). The option
from the user matters for the dnf call in dom0 only.
Especially, sending --downloadonly breaks downloading updates via
debian-10, which uses yumdownloader, as it doesn't have --downloadonly
option.
This is mostly relevant for R4.0 -> R4.1 upgrade (and maybe some future
too?), as the process uses --downloadonly option internally.
QubesOS/qubes-issues#5685
> dom0-update: do not send --downloadonly option to the updatevm

- dom0-updates/qubes-cached.repo
If `repo_gpgcheck=1` is set globally in dom0, updates break.  They will also break if DNF gets fixed to check signatures against the specific OpenPGP key specified in the repository file, instead of against the RPM keyring.  This fixes both problems.
> Fix dom0 updates if `repo_gpgcheck=1` is globally set

- dom0-updates/qubes-dom0-update
This provides an option to prevent the UpdateVM's console window from
exiting until the user takes action.
> Allow viewing the UpdateVM output on success

- dom0-updates/qubes-dom0-update
In my dom0  I have repos installed which require custom yum variables.
This change is required to allow access to those variables on the update vm.
This works for me right now, but maybe there is a better way to solve this.
> Make dom0 yum variables available in updatevm

- qubes-rpc/qubes.repos.Disable
- qubes-rpc/qubes.repos.Enable
- qubes-rpc/qubes.repos.List
Template repositories are now defined in /etc/qubes/repo-templates -
handle this location too.
QubesOS/qubes-issues#7252
> Make qubes.repo.* services handle new template repos location

- dom0-updates/qubes-dom0-update
The updatevm script does need this option too, for two reasons:
- to skip downloading updates if only check was requested
- to report updates availability via exit code
The second point is critical for setting 'updates-available' flag.
Fixs QubesOS/qubes-issues#7417
> qubes-dom0-update: Pass --check-only option to the updatevm too

- dom0-updates/qubes-dom0-update
This may mess with exit code (critical for setting updates-available
flag), but also may be confusing when started from cron.
This is the last part of dom0 updates notification fix.
Fixes QubesOS/qubes-issues#7437
> dom0-update: do not show xterm with update check process

- dracut/modules.d/90qubes-pciback/qubes-pciback.sh
When booting Linux directly, binding devices to xen-pciback will fail.
Do not fail the boot in this case.
https://github.com/QubesOS/qubes-issues/issues/7390#issuecomment-1086745690
> dracut: do not fail native (non-Xen) boot

- dracut/modules.d/90extra-modules/module-setup.sh
In Linux 5.15 it got renamed to 'bochs'. Adjust the dracut module to
include both - instmods will ignore non-existing one.
> dracut: adjust 'bochs-drm' module name

- cpu-microcode-info/cpu-microcode-info
- rpm_spec/core-dom0-linux.spec.in
This is a small script to read the CPU model info and the loaded
microcode version in the format used by Intel's microcode update
packages readme [1].
[1]: https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/blob/main/releasenote.md#microcode-20220510
> Add cpu-microcode-info

- dom0-updates/qubes.ReceiveUpdates.policy
- qubes-rpc-policy/90-default-linux.policy
- qubes-rpc-policy/qubes.repos.Disable
- qubes-rpc-policy/qubes.repos.Enable
- qubes-rpc-policy/qubes.repos.List
- qubesappmenus/qubes.SyncAppMenus.policy
- rpm_spec/core-dom0-linux.spec.in
1. Convert qubes.ReceiveUpdates to 90-default-linux.policy
2. Move qubes.SyncAppMenus to 90-default.policy in core-admin
3. Drop qubes.repos.*, since those are "deny" by default anyway
QubesOS/qubes-issues#8000
> Convert policy to the new format

- file-copy-vm/qvm-copy-to-vm
This can cause the copy to hang for no good reason.  Also unconditionally filter escape characters in stderr.
Fixes: QubesOS/qubes-issues#8239.
> qvm-copy-to-vm: disable wait for GUI session

- dom0-updates/qfile-dom0-unpacker.c
- dom0-updates/qubes-receive-updates
qfile-dom0-unpacker does not need to support unpacking directories or symbolic links when receiving updates, so do not allow it to do so.
> Safer unpacking of files in dom0

- dom0-updates/qubes-dom0-update
Write `script` output to /dev/null, it doesn't need to persist. It's
main purpose is printing to the console, which is done regardless of the
output file.
Fixes QubesOS/qubes-issues#8304
> dom0-update: avoid writing 'typescript' file

- dom0-updates/qubes-dom0-updates.cron
If the `qubes-dom0-update --check-only` fails it's better to not update the `last-updates-check` feature to indicate a problem to a user.
Related to: https://github.com/QubesOS/qubes-core-admin-linux/pull/129
> qubes-vm-update: do not update last-updates-check if checking updates fails

- qubes-rpc/qubes.repos.Disable
- qubes-rpc/qubes.repos.Enable
Qrexec service is dom0 are called as normal user. Template repos may be
writable by that user, but dom0 repos not really. Make the calls work as
non-root user too, by automatically using sudo in that case.
Fixes QubesOS/qubes-issues#8349
> Make qubes.repos.* work when called as non-root too

- dom0-updates/qubes-dom0-update
Reboot is necessary after major Xen update, but with --downloadonly it
wasn't performed yet.
QubesOS/qubes-issues#7832
> qubes-dom0-update: do not prompt for reboot on --downloadonly call

- vmupdate/agent/source/dnf/dnf_api.py
When an update is installed from a given repository for the first time,
its signing key may not be imported yet. Import the key as DNF would do,
and retry the signature check.
> qubes-vm-update/dnf: import signing key if needed

- rpm_spec/core-dom0-linux.spec.in
- system-config/usbguard.service
They don't have any secrets, and having them root-only breaks building
initramfs as non-root.
QubesOS/qubes-issues#8206
> Relax permissions of usbguard configs

- rpm_spec/core-dom0-linux.spec.in
- system-config/10_pipewire-high-latency.conf
PipeWire doesn't realize dom0 is a virtual machine and sets its quantums too low, resulting in xruns and unusably bad audio quality.
> Work around a bug in PipeWire

- vmupdate/agent/source/apt/apt_cli.py
apt-get update exits with code 100 on error, but updater as a whole uses
this code for "no update". Translate code 100 in this place to 1.
Fixes QubesOS/qubes-issues#8898
> qubes-vm-update: fix false negative on apt-get update error

- dom0-updates/qfile-dom0-unpacker.c
This is totally possible during distupgrade.  I hit the issue myself. It wasn't even hard — I just have KDE stuff on my system, which is quite a lot of packages over the base dom0 system setup.
> Up the limit of files downloaded during a dom0 update.

- vmupdate/agent/source/plugins/updatesproxy_fix.py
Updating templates without qubes-core-agent-networking package failed because qubes.UpdateProxy file doesn't exist. This commit will fixes it.
> fix #9025 hotfix for some minimal templates

- vmupdate/vmupdate.py
When qubes-vm-update is called as root, the log would be created as
root, breaking the usage by normal user. Fix this by trying to make the
log writable by the "qubes" group. This may fail if the tool is called
as non-root user, but that's okay - at this point the current
permissions were enough to start the tool.
> vmupdate: make log group-writable

- vmupdate/qube_connection.py
We should use `/usr/bin/python3` or `/bin/python3`. Using just `python3` can break updater.
fixes QubesOS/qubes-issues/issues/9200
> updater: use the same python interpreter as in `entrypoint.py`

- dom0-updates/qubes-dom0-update
Fixes: https://github.com/QubesOS/qubes-issues/issues/885
> qubes-dom0-update could check whether /boot is mounted

- doc/tools/qubes-vm-update.rst
- vmupdate/agent/entrypoint.py
- vmupdate/agent/source/apt/apt_api.py
- vmupdate/agent/source/common/exit_codes.py
- vmupdate/agent/source/common/package_manager.py
- vmupdate/agent/source/common/process_result.py
- vmupdate/agent/source/dnf/dnf_api.py
- vmupdate/tests/conftest.py
- vmupdate/tests/test_vmupdate.py
- vmupdate/update_manager.py
- vmupdate/vmupdate.py
partially solves issue https://github.com/QubesOS/qubes-issues/issues/9196
related to https://github.com/QubesOS/qubes-doc/pull/1408
> Standardization of return codes + man page

- vmupdate/agent/source/plugins/manage_rpm_macro.py
- vmupdate/agent/source/plugins/updatesproxy_fix.py
- vmupdate/agent/source/utils.py
references https://github.com/QubesOS/qubes-issues/issues/9195
> Remove deprecated pkg-resources, replace with packaging

- dom0-updates/qubes-dom0-update
fixes: https://github.com/QubesOS/qubes-issues/issues/6345
> qubes-dom0-update: prevent concurrent execution

- vmupdate/agent/source/apt/apt_api.py
- vmupdate/agent/source/apt/apt_cli.py
If there is an `apt-get update` running in the background (for example
periodical updates check), running another would fail. Since `apt-get`
itself doesn't have an option to wait for the lock, wait for it in the
updater tool. It's not perfect - there is still a window where another
apt-get instance can start, but at least this will handle the (more
common) situation when it's already running.
> vmupdate: wait for other apt-get to complete

- vmupdate/agent/source/plugins/fix_meminfo_writer_label.py
The current plugin always run if the system is detected as fedora. But, SELinux is not always installed (minimal templates for example) or it can be intentionally disabled by the user, meaning the script will throw a chcon error in the update log. Fix that by first checking if SELinux is installed, and then check if the status is Enforcing/Permissive.
https://github.com/QubesOS/qubes-issues/issues/9663
> vmupdate: Fix SELinux plugin detection

- vmupdate/agent/source/apt/apt_cli.py
apt-get uses fcntl F_SETLK for locking, not flock(). Update the function
accordingly.
Fixes: 8fa2929 "vmupdate: wait for other apt-get to complete"
> vmupdate: fix waiting for the other apt-get process

- vmupdate/agent/source/plugins/__init__.py
Ensure deterministic load order, but also allow a bit of control over
that order. There may be plugin that wants to be loaded before others.
> vmupdate: load plugins in sorted order

- vmupdate/agent/source/plugins/bookworm_backports.py
Firmware packages in standard Debian repo are too old for recent
kernels, and recent hardware in general. This affects all kernel-latest
versions, but also soon-to-be-default kernel-6.12. This is at least
necessary to support wifi network in NovaCustom laptops, but other
modern systems need that too.
Fresh template builds have firmware from bookworm-backports already
selected, but do that for older versions too.
Thanks @aronowski for the hint on apt properties.
Fixes QubesOS/qubes-issues#9815
> Update firmware packages from bookworm-backports on Debian 12

- vmupdate/agent/source/apt/apt_cli.py
This is the case after fresh template installation.
Fixes QubesOS/qubes-issues#9857
> vmupdate: don't fail if apt lock file doesn't exist

- dom0-updates/qubes-dom0-update
- rpm_spec/core-dom0-linux.spec.in
Some small programs uses Zenity to show dialogs.
Fixes: QubesOS/qubes-issues#7280
> add Zenity to dependencies

- vmupdate/vmupdate.py
The feature `qubes-vm-update --apps` does not work as it never selects any AppVM, the point of this flag is to update all running AppVM so you don't have to restart them. Of course, and it's in the documentation, changes will be lost after reboot, this does not prevent from updating according templates, but this allows you to update without stopping work / running stuff.
After this change, it only works with the associated flag `--force-update` because there are no known information about available updates for an appvm, and this is not pulled from the template information either.
Thanks @alimirjamali for the diff!
> vmupdate: fix --apps flag

- dom0-updates/qubes-receive-updates
Removing arbitrary package length requirement (127) chars.
Rpm works just fine even with package names longer than 127 chars.
> qubes-receive-updates: Remove arbitrary package name length requirement.
